### DISCUSSION TITLE
List of tags as taxonomy pages

### DISCUSSION THREAD

**Discussion by sn00py1310** [colinwilson/lotusdocs#154] [Feature Requests]
As an expansion to #24 it would be great if the tags had taxonomy pages.
Including:
- an overview over all tags
- on each tags term site an overview of all documents with a specific tag

If the tags should be under the `docs` directory, you would need to add something like that to your `hugo.toml`
```toml
# See https://github.com/gohugoio/hugo/issues/11846
# See https://discourse.gohugo.io/t/re-new-permalinks-config-in-0-115-x-permalinks-term/45218

[taxonomies]
  docs-tags = "docs-tags"

[permalinks.taxonomy]
   docs-tags = "docs/tags/"
[permalinks.term]
   docs-tags = "docs/tags/:slug"
```
