### DISCUSSION TITLE
External reference link in menu

### DISCUSSION THREAD

**Discussion by artberger** [colinwilson/lotusdocs#178] [Q&A]
Is there a way to add an external reference link in the menu? I want one of the left-hand navigation menu pages to just link out to an external webpage.

I tried adding something like this in the `.toml` file, but it didn't seem to add any entry to the navigation menu.
```toml
[menus]
  [[menus.main]]
    name = 'Hugo'
    pre = '<i class="fa fa-heart"></i>'
    url = 'https://gohugo.io/'
    weight = 30
    [menus.main.params]
      rel = 'external'
```
