### DISCUSSION TITLE
Changing Primary Menu Entry Name

### DISCUSSION THREAD

**Discussion by ghost** [colinwilson/lotusdocs#31] [Q&A]
I'm looking to change the name of the primary menu entry "Docs" to "Code". 

To do this, I've made the below changes in `hugo.toml`:

```toml
baseURL = 'https://example.com/'
languageCode = 'en-us'
title = 'Website Title'

contentDir = "content"
enableEmoji = false
enableGitInfo = true
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    title = "Some Title"
    languageName = "English"
    weight = 10

[module]
    [module.hugoVersion]
        extended = true
        min = "0.100.0"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false


[menu]
[[menu.primary]]
    name  = "Code"
    url = "code/"
    identifier = "code"
    weight = 10

[params]
  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Inter"     # Default is System font
  secondary_font  = "Inter"     # Default is System font
  mono_font       = "Fira Code" # Default is System font

    [params.social]
        rss = true                    # show rss icon with link

    [params.code] # Parameters for the /docs 'template'
        title           = "Lotus Docs Example Site"           # default html title for documentation pages/sections

        pathName        = "code"                            # path name for documentation site | default "docs"

        themeColor      = "blue"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan

        darkMode        = false                                # enable dark mode option? default false

        prism           = true                                # enable syntax highlighting via Prism

        sidebarIcons    = true                                # enable sidebar icons? default false
        breadcrumbs     = true                                # default is true
        backToTop       = true                                # enable back-to-top button? default true

        # ToC
        toc             = true                                # enable table of contents? default is true
        tocMobile       = true                                # enable table of contents in mobile view? default is true
        scrollSpy       = true                                # enable scrollspy on ToC? default is true

        # front matter
        descriptions    = true                                # enable front matter descriptions under content title?
        titleIcon       = true                                # enable front matter icon title prefix? default is false

        # content navigation
        navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
        navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

        listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description

    [params.flexsearch] # Parameters for FlexSearch
        enabled         = true
```

And the directory structure of in `mywebsite/content/` looks like:

```
.
└── code
    ├── _index.md
    ├── exercises
    │   ├── _index.md
    │   ├── some-topic-1
    │   │   ├── _index.md
    │   │   ├── file-2.md
    │   │   └── file-1.md
    │   ├── some-topic-2
    │   │   ├── _index.md
    │   │   ├── file-4.md
    │   │   └── file-3.md
    │   └── some-topic-3
    │       ├── _index.md
    │       └── file-5.md
    └── overview.md
```

On the homepage, when I click on "Code", I see "Page not found :(".

Appreciate any help on this.
