### ISSUE TITLE
CJK language search does not work in flexsearch

### ISSUE THREAD

**Issue by staeho-3rd** [colinwilson/lotusdocs#167]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for support

### Describe the bug

Searching for English words works fine, but searching for words in CJK languages yields no results.

### Expected behavior

should be able to enter words from CJK languages as well as English words and still get search results.

### Screenshots

![lotus-1](https://github.com/colinwilson/lotusdocs/assets/74173303/4b49a891-2e7c-4454-8495-91019b2fffe8)
![lotus-11](https://github.com/colinwilson/lotusdocs/assets/74173303/58fec09c-0aac-46bb-b04d-aa4943bd64ef)

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome
- Browser Version: 112
```

**Comment by jikunchong** [comment]
me too.  How to modify the script `layouts/partials/docs/footer/flexsearch.html`?

```javascript
    var index = new FlexSearch.Document({
        // charset: "latin:default",
        charset: "cjk:default",
        language: 'zh',
        async: true,
        tokenize: {{ .Site.Params.flexsearch.tokenize | default "forward" }},
        minlength: {{ .Site.Params.flexsearch.minQueryChar | default 0}},
        cache: {{ .Site.Params.flexsearch.cache | default 100 }},
        optimize: {{ .Site.Params.flexsearch.optimize | default true }},
        document: {
        id: 'id',
        store: [
            "href", "title", "description"
        ],
        index: ["title", "description", "content"]
        }
    });
```

`hugo.toml`:
```toml
    [params.flexsearch] # Parameters for FlexSearch
        enabled             = true
        tokenize            = "full"                       # full, forward
        #optimize            = true
        #cache               = 100
        #minQueryChar        = 2 # default is 0 (disabled)
        maxResult           = 10 # default is 5
        # searchSectionsIndex = []
```

<img width="2120" height="880" alt="Image" src="https://github.com/user-attachments/assets/eaf4e18a-e5b5-4065-b32a-143764ab6578" />
